pipeline:
  name: Build ank_OpencartFramework
  identifier: Build_anum1297_ank_OpencartFramework_1790937680506
  projectIdentifier: Opencart
  orgIdentifier: default
  stages:
    - stage:
        name: Playwright E2E
        identifier: Playwright_E2E
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install and run Playwright tests
                  identifier: Install_and_run_Playwright_tests
                  spec:
                    image: mcr.microsoft.com/playwright:v1.63.0-noble
                    shell: Bash
                    envVariables:
                      EMAIL_SEND: "true"
                      SMTP_USER: <+secrets.getValue("smtp_user")>
                      SMTP_PASSWORD: <+secrets.getValue("smtp_password")>
                      EMAIL_TO: <+secrets.getValue("email_to")>
                    command: |-
                      npm ci
                      npx bddgen test
                      BROWSER=chromium xvfb-run -a npx playwright test --project=chromium
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - test-results/junit.xml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1790937521871
        repoName: anum1297/ank_OpencartFramework
        build: <+input>
