# Browser configuration
browser=chrome
# browser=firefox
# browser=edge
# browser=msedge
# browser=chrome,firefox,edge
# browser=all

# URL of the application
baseURL=https://naveenautomationlabs.com/opencart/

# Email configuration
emailSend=false
EMAIL_SUBJECT=OpenCart Automation - Test Execution Summary

# Other configuration values
testEnvironment=QA

#products to be purchased
product1=HP LP3065